---
name: Upgrade tests
on:
  push:
    paths-ignore:
      - 'web/**'
  pull_request:
    paths-ignore:
      - 'web/**'

jobs:
  generateVersions:
    runs-on: ubuntu-latest
    steps:
      - run: curl --version
      - run: jq --version
      - name: Generate matrix with all released versions
        id: set-matrix
        run: |
          echo "matrix=$(
            curl https://api.github.com/repos/owncast/owncast/releases |
            jq '[ .[] | .tag_name ]'
          )" >> $GITHUB_OUTPUT
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
  checkUpdate:
    runs-on: ubuntu-latest
    needs: generateVersions
    strategy:
      matrix:
        version: ${{ fromJson(needs.generateVersions.outputs.matrix) }}
    steps:
      - run: echo ${{ matrix.version }}
