---
name: Upgrade tests
on:
  push:
    paths-ignore:
      - 'web/**'
  pull_request:
    paths-ignore:
      - 'web/**'

jobs:
  generateVersions:
    runs-on: ubuntu-latest
    steps:
      - run: curl --version
      - run: jq --version
      - name: Generate matrix with all released versions
        id: set-matrix
        run: |
          curl https://api.github.com/repos/owncast/owncast/releases |
          jq '.[] | .tag_name'
    # outputs:
    #   matrix: ${{ steps.set-matrix.outputs.matrix }}
